# Generated by Django 2.2.7 on 2019-11-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='reserva',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
