# Generated by Django 2.2.7 on 2019-11-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_auto_20191130_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='estado',
            field=models.IntegerField(default='0'),
        ),
    ]
