# Generated by Django 2.2.7 on 2019-11-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_torneio_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='numFalhasJogos',
        ),
        migrations.AddField(
            model_name='jogador',
            name='numFalhasJogo',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
